### ISSUE TITLE
Add a reload icon

### ISSUE THREAD

**Issue by Kilian** [danklammer/bytesize-icons#1]
Awesome set of icons! 

Would it be possible to add a 'reload' icon? An almost-complete circle with an arrow at the end, or two half-circles that both have an arrow (variations: https://www.google.com/search?q=reload+icon&tbm=isch )

**Comment by ScholtenSeb** [comment]
#2

**Comment by danklammer** [comment]
Reload icon has been added. Thanks for the feedback!
