### ISSUE TITLE
Feed icon

### ISSUE THREAD

**Issue by ghost** [danklammer/bytesize-icons#21]
Because RSS is all the rage.

**Comment by jhabdas** [comment]
Found a suitable replacement icon already bundled in the pack.

<img width="410" alt="screen shot 2019-01-22 at 5 00 05 pm" src="https://user-images.githubusercontent.com/440298/51523736-43d4e000-1e67-11e9-9c09-512cbe0ad92b.png">

**Comment by thisconnect** [comment]
feed rss icon would be nice, please keep this request open :)

**Comment by danklammer** [comment]
I will be adding this in the next version.

**Comment by danklammer** [comment]
Added Feed icon to v1.4.

**Comment by thisconnect** [comment]
thanks!
