### ISSUE TITLE
Sun and moon icons

### ISSUE THREAD

**Issue by ghost** [danklammer/bytesize-icons#22]
Obviously this is a slippery slope, but I wanted to put this one out there given the number of themes which are introducing a toggle for daytime and nighttime reading.

**Comment by jhabdas** [comment]
Or, combine both into a semicircle for a single icon

<img width="80" alt="screen shot 2019-02-02 at 5 15 05 pm" src="https://user-images.githubusercontent.com/440298/52162375-1cef9700-270e-11e9-877b-1208318756fb.png">

**Comment by danklammer** [comment]
@jhabdas Sorry for the delay. I do like this idea! I am exploring this for my next release.

Here is one potential version:

```html
<svg xmlns="http://www.w3.org/2000/svg" id="i-moon" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
    <circle fill="none" cx="16" cy="16" r="14" />
    <path stroke-width="0" stroke-miterlimit="10" fill="currentColor" d="M16 5 L16 27 C9 27 5 21.5 5 16 5 10.5 10 5 16 5Z" />
</svg>
```

**Comment by jhabdas** [comment]
You da man Mr Dan!

**Comment by jhabdas** [comment]
Looks absolutely fantastic and I'm looking forward to using it. Thanks, Dan.

**Comment by danklammer** [comment]
Added Moon icon to v1.4 which can be used for both Dark Mode and/or Do Not Disturb.

**Comment by XhmikosR** [comment]
@danklammer: have you thought about a sun or bulb icon too?
