### ISSUE TITLE
Icons are not visible in certain applications

### ISSUE THREAD

**Issue by M4verick256** [danklammer/bytesize-icons#32]
Hello, 

i really appreciate the work you made but i can't use it. I can see all of the icons in web browsers like Firefox or Chromium, but i can't open checkmark.svg in Inskcape, it's just a blank transparent image, there are no shapes at all. Same with Image Wiever in Ubuntu. Maybe you've used some kind of svg format that is not fully supported yet?

**Comment by danklammer** [comment]
@M4verick256, these SVGs are supported in Inkscape and other applications. It's likely the Stroke that is set to transparent or white making it seem like it's not rendering. In Inkscape go to Object > Fill & Stroke (⌘⇧F) to adjust stroke color/width.
