### ISSUE TITLE
Do you take PRs for new icons?

### ISSUE THREAD

**Issue by brandondurham** [danklammer/bytesize-icons#5]
Would love to take a shot at adding a book. Do you take pull requests for new icons?

**Comment by amilajack** [comment]
This would be great!

**Comment by danklammer** [comment]
@brandondurham Sure, feel free! I actually made a book icon but wasn't 100% sold on how it turned out. Maybe I'll still add it to the collection. http://jsbin.com/muzowu/edit?html,output

```html
<svg id="i-book" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
    <path d="M16 7 C16 7 9 1 2 6 L2 28 C9 23 16 28 16 28 16 28 23 23 30 28 L30 6 C23 1 16 7 16 7 Z M16 7 L16 28" />
</svg>
```

**Comment by jlala** [comment]
hi! Can be used on native react?

**Comment by amilajack** [comment]
@jlala Yes, it can be.
