### ISSUE TITLE
Clarify whether attribution is required

### ISSUE THREAD

**Issue by Nateowami** [danklammer/bytesize-icons#7]
As I see it, the most confusing part of the MIT license as it applies to this project, is this line:  
>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

So what counts as copies or substantial portions? Suppose you take a few icons and add them to a webpage. It appears, then, that attribution is required. But what kind of attribution? On the page, or in the code? Is the software just the code, or also the rendered icons?

I think it's for this reason that most open fonts use the [SIL Open Font License](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL), including Font Awesome, though Font Awesome no longer requires attribution.

I believe the MIT license could hold some people back from using the icons, even in ways that the author would deem acceptable, simply due to ambiguity of the license. Personally, I would favor an attribution-not-required license, simply because it's not nice to have to make sure you have attribution if you just copy an icon or two into a page (attribution in the source code is a different matter; I don't really have an opinion).

Very nice icons by the way. I really love being able to copy a couple lines instead of adding a dependency.

**Comment by danklammer** [comment]
@Nateowami Good points. While this project will remain under the MIT license for now, attribution is encouraged but not required.

I added a line to the README to clarify.

**Comment by Nateowami** [comment]
@danklammer Thanks. That's a helpful change.

**Comment by jhabdas** [comment]
That line is [known as](https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html#notice-condition) the _Notice Condition_. If you're interested in understanding the MIT license this is worth your time. Here's a quick excerpt from the _Warranty Disclaimer_ section:

> Lawyers have long suffered under the delusion that writing anything in <samp>ALL-CAPS</samp> meets the conspicuous requirement. That isn’t true.

**Comment by jhabdas** [comment]
That line is [known as](https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html#notice-condition) the _Notice Condition_. If you're interested in understanding the MIT license Ken's writing is worth your time. Here's an excerpt from the _Warranty Disclaimer_ section:

> Lawyers have long suffered under the delusion that writing anything in <samp>ALL-CAPS</samp> meets the conspicuous requirement. That isn’t true.

**Comment by jhabdas** [comment]
@danklammer I think I have a solution to the licensing conundrum here. [0BSD](https://tldrlegal.com/license/bsd-0-clause-license). With Zero Clause BSD those using your software can omit the license and choose to attribute if they like (not a requirement of the current license anyway).

**Comment by balibebas** [comment]
FYI https://github.com/edent/SuperTinyIcons/issues/214

**Comment by balibebas** [comment]
> While this project will remain under the MIT license for now, attribution is encouraged but not required.

That's thoughtful, but not legally binding. My suggestion would be to change to an unconditional license such as the 0BSD or Unlicense.
